// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Logo(size string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<svg width=\"30\" height=\"30\" viewBox=\"0 0 120 120\" class=\"looka-1j8o68f\"><defs id=\"SvgjsDefs1319\"></defs> <g id=\"SvgjsG1320\" featurekey=\"symbolContainer\" transform=\"matrix(1,0,0,1,0,0)\" fill=\"#e51065\"><rect width=\"110\" height=\"109\"></rect></g> <g id=\"SvgjsG1321\" featurekey=\"monogramFeature-0\" transform=\"matrix(1.8430753250050795,0,0,1.8430753250050795,15.466031993639358,-17.069509952010947)\" fill=\"#f9dacf\"><path d=\"M29.28 37.08 c6.9 0.96 11.16 5.16 11.16 10.92 c0 7.08 -6.24 12 -20.1 12 l-16.44 0 c-0.84 0 -1.44 -0.42 -1.44 -1.14 l0 -0.24 c0 -1.68 2.4 -2.4 2.4 -5.16 l0 -29.52 c0 -2.76 -2.4 -3.48 -2.4 -5.16 l0 -0.24 c0 -0.72 0.6 -1.14 1.44 -1.14 l16.62 0 c10.8 0 15.72 4.8 15.72 10.8 c0 4.5 -2.76 7.8 -6.96 8.88 z M15.66 24.72 l0 7.56 c0 1.98 1.32 3.12 3.24 3.12 l3 0 c3.06 0 5.04 -2.22 5.04 -5.64 c0 -5.16 -2.7 -8.16 -6.78 -8.16 l-1.68 0 c-1.56 0 -2.82 0.72 -2.82 3.12 z M23.04 55.8 c3.84 0 6 -2.52 6 -6.24 c0 -4.44 -3.66 -9.96 -10.86 -9.96 l-2.52 0 l0 11.1 c0 2.88 1.74 5.1 4.5 5.1 l2.88 0 z\"></path></g></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
